context:
  version: "3.4.1"

package:
  name: napi-rs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@napi-rs/cli/-/cli-${{ version }}.tgz
  sha256: a884f96b938398e488c567d5b59769d17e05bf980878b3495f083a0cebb0de9a

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - napi --help

about:
  license: MIT
  license_file: LICENSE
  summary: A framework for building compiled Node.js add-ons in Rust via Node-API
  homepage: https://github.com/napi-rs/napi-rs
  repository: https://github.com/napi-rs/napi-rs

extra:
  recipe-maintainers:
    - danielnachun
