context:
  version: "3.8.3"

package:
  name: napi-rs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@napi-rs/cli/-/cli-${{ version }}.tgz
  sha256: 9b1c2c9cf92bb4ef8d49e3411f9637e2d60174d6a981d7e7e7d3988911d9a6e4

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - napi --help

about:
  license: MIT
  license_file: LICENSE
  summary: A framework for building compiled Node.js add-ons in Rust via Node-API
  homepage: https://github.com/napi-rs/napi-rs
  repository: https://github.com/napi-rs/napi-rs

extra:
  recipe-maintainers:
    - danielnachun
