context:
  version: "3.8.4"

package:
  name: napi-rs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@napi-rs/cli/-/cli-${{ version }}.tgz
  sha256: bb146318c609e2f0d87711a55772438d9096dd5127bc74e3b2839b73b75e89e5

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - napi --help

about:
  license: MIT
  license_file: LICENSE
  summary: A framework for building compiled Node.js add-ons in Rust via Node-API
  homepage: https://github.com/napi-rs/napi-rs
  repository: https://github.com/napi-rs/napi-rs

extra:
  recipe-maintainers:
    - danielnachun
