context:
  version: "3.7.3"

package:
  name: napi-rs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@napi-rs/cli/-/cli-${{ version }}.tgz
  sha256: 64590af525c03faaf243226d3dba2bccf80bd343d78a17f9fcb78590cdc2a2fb

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - napi --help

about:
  license: MIT
  license_file: LICENSE
  summary: A framework for building compiled Node.js add-ons in Rust via Node-API
  homepage: https://github.com/napi-rs/napi-rs
  repository: https://github.com/napi-rs/napi-rs

extra:
  recipe-maintainers:
    - danielnachun
